# Project information
site_name: LSDHH Site Documentation
site_url: https://nashville-public-library.github.io/lsdhh-documentation/
site_description: Content creator and developer documentation for the LSDHH / Ask Sandy website. 

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode
    - scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode
  font: false

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - Overview: index.md
  - Add Content: 
      - add-content/event.md
      - add-content/helpful-links.md
      - add-content/homepage-slides.md
      - add-content/job-posting.md
      - add-content/knowledge-base-item.md
      - add-content/licensure.md
      - add-content/material.md
  - How Site is Built:
      - how-site-is-built/block-types.md
      - how-site-is-built/conditional-fields.md
      - how-site-is-built/content-mod-workflow.md
      - how-site-is-built/content-types.md
      - how-site-is-built/feed-types.md
      - how-site-is-built/flags.md
      - how-site-is-built/media-types.md
      - how-site-is-built/menus.md
      - how-site-is-built/message-templates.md
      - how-site-is-built/paragraph-types.md
      - how-site-is-built/roles-permissions.md
      - how-site-is-built/taxonomies.md
      - how-site-is-built/views.md
      - how-site-is-built/webforms.md
  - Moderate Content:
      - moderate-content/event.md
      - moderate-content/job-posting.md
      - moderate-content/moderation-workflow.md
      - moderate-content/resource.md
  - User Permissions and Approvals:
      - user-permissions-and-approvals/new-user.md
      - user-permissions-and-approvals/roles-permissions.md


copyright:
  c 2023 Metropolitan Government of Nashville and Davidson County, GNU GENERAL PUBLIC LICENSE.