# Project information
site_name: LSDHH Site Documentation
site_url: https://nashville-public-library.github.io/lsdhh-documentation/
site_description: Content creator and developer documentation for the LSDHH / Ask Sandy website. 

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode
    - scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode
  font: false

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - Introduction: index.md
  - Add / Manage Content:
      - index.md
      - event.md
      - helpful-links.md
      - homepage-slides.md
      - job-posting.md
      - knowledge-base-item.md
      - licensure.md
      - material.md
  - Admin:
      - block-types.md
      - conditional-fields.md
      - content-mod-workflow.md
      - content-types.md
      - feed-types.md
      - flags.md
      - media-types.md
      - menus.md
      - message-templates.md
      - paragraph-types.md
      - roles-permissions.md
      - taxonomies.md
      - views.md
      - webforms.md

copyright:
  c 2023 Metropolitan Government of Nashville and Davidson County, GNU GENERAL PUBLIC LICENSE.