# Project information
site_name: LSDHH Site Documentation
site_url: https://nashville-public-library.github.io/lsdhh-documentation/
site_description: Content creator and developer documentation for the LSDHH / Ask Sandy website. 

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode
    - scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode
  font: false

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - Overview: index.md
  - Add / Manage Content: 
      - add-manage-content/event.md
      - add-manage-content/helpful-links.md
      - add-manage-content/homepage-slides.md
      - add-manage-content/job-posting.md
      - add-manage-content/knowledge-base-item.md
      - add-manage-content/licensure.md
      - add-manage-content/material.md
  - Admin:
      - admin/block-types.md
      - admin/conditional-fields.md
      - admin/content-mod-workflow.md
      - admin/content-types.md
      - admin/feed-types.md
      - admin/flags.md
      - admin/media-types.md
      - admin/menus.md
      - admin/message-templates.md
      - admin/paragraph-types.md
      - admin/roles-permissions.md
      - admin/taxonomies.md
      - admin/views.md
      - admin/webforms.md

copyright:
  c 2023 Metropolitan Government of Nashville and Davidson County, GNU GENERAL PUBLIC LICENSE.